spring:
  thymeleaf:
    cache: true

nest:
  nestTokenAddress: "0x04abeda201850ac0124161f037efd70c74ddc74c"
  # USDT quote mining contract address
  nestMiningAddress: "0x03dF236EaCfCEf4457Ff7d6B88E8f00823014bcd"
  # Ntoken quote mining contract address
  ntokenMiningAddress: "0xC2058Dd4D55Ae1F3e1b0744Bdb69386c9fD902CA"
  # Ntoken manages the contract address
  nTokenControllerAddress: "0xc4f1690eCe0145ed544f0aee0E2Fa886DFD66B62"

  # Test 1 million, mainnet 5 million, NToken issue greater than this value, enable post2
  nTokenMaxTotalSupply: 5000000000000000000000000
  # Calculate the quoted fee ratio
  miningFeeRateInflateFactor: 10000
  # Eat single handling fee ratio
  biteFeeRate: 0
  # Eat single quoted assets to increase multiple
  biteInflateFactor: 2
  # When you eat a single meal, your NEST increases by multiple, doubling every time you eat a single meal, no matter how long you eat a single meal
  biteNestInflateFactor: 2
